apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: app-deployment
  template:
    metadata:
      labels:
        name: app-deployment
      name: app-pod
    spec:
      containers:
      - name: app-container
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        image: quay.io/jitesoft/alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: [ "while true; do sleep 10000; done;" ]
        # Guaranteed pod
        resources:
           limits:
             memory: "100Mi"
             cpu: "2000m"
             example.com/resource: 1
